Multiple additions to Practice Mode (1 Player) + 9 Ball table colors
VRCBilliards/vrcbce pull request #128
Opened 2021-11-06 23:53 UTC by Codel1417

Added

- Shot Undo / Redo System
- Shot Preview System
- Shot Physics Replay
- 9 Ball affects table lights

Removed
- Bit Shifting
- uints

Fixed
- Cue ball spinning in pocket #121

2021-11-14 12:25 UTC, Legoman99573 commented on Assets/VRCBilliardsCE/Scripts/PoolStateManager.cs
> +                int isAccurate = isMoreAccurate ? 2 : 1;
Shouldn't the sim not run twice on quest only regardless of settings or will this cause a sync problem with simulation?

2021-11-14 12:25 UTC, Legoman99573 commented on Assets/VRCBilliardsCE/Scripts/PoolStateManager.cs
> +        public bool isMoreAccurate = false;
Would be better description for this option as it would warn for quest users what could happen: 
```cs
[Tooltip("Runs the simulation twice per frame at the slight cost of performance. This can cause issues on quest with multiple users in the room at once.")]
```

2022-01-10 09:26 UTC, Legoman99573 requested changes
Not bad, but would need to rebase as its 34 commits behind. Just incase something breaks, it will need further testing incase something conflicts that will cause the prefab to crash.

2022-01-10 10:38 UTC, FairlySadPanda commented
Yup, Floof has a tonne to do getting their work up-to-date but they've gotten started.

2022-05-18 16:03 UTC, FairlySadPanda commented
@Codel1417 - please either fix this PR or close it within the next week.

2022-05-18 18:14 UTC, Legoman99573 commented
Probably could fork it and compare changes to master and adjust accordingly if needed. Would require alot of testing to make sure everything works correctly.

2022-05-19 06:00 UTC, closed without merging

2022-05-19 12:55 UTC, Legoman99573 commented
> Plan to remove bitshifting again if it isnt already

Removed in https://github.com/VRCBilliards/vrcbce/commit/a13907b8b4a9cc65eced1c9e6241e4e6ca4befd2